/* Pulse LED using PWM generated by Timer/Counter hardware peripheral. */
/* Remember that there are more ways to pulse a LED - e.g. using 555 Timer chip. */
#include <avr/io.h>      // Defines pins, ports, etc
#include <util/delay.h>  // Functions to waste time
#include <avr/interrupt.h>  // "ISR" macro, and more
#include <avr/sleep.h>   // Power Management and Sleep Modes
#include "pin_config.h"

#define PULSE_PRESCALER 10  // PULSE_FREQUENCY = PWM_Freq / PULSE_PRESCALER


uint8_t cycle = 0;
int8_t step = 1;

ISR(TIMER1_OVF_vect) {  // Run every time Timer1 overflows = PWM cycle finishes
  if (cycle == PULSE_PRESCALER) {  // Run every PULSE_PRESCALER PWM cycle finishes
    cycle = 0;
    OCR1A += step;

    if (OCR1A == 0) step = 1;
    else if (OCR1A == 255) step = -1;
  }
  else cycle++;
}

static inline void initTimer1PWM(void) {
  // Generate PWM on pin OC1A (PB1) by setting Timer1 Compare Output Mode to Fast PWM
  TCCR1A |= (1 << WGM10);   // Fast PWM mode, 8-bit  (part 1)
  TCCR1B |= (1 << WGM12);   // Fast PWM mode, 8-bit  (part 2)
  TCCR1B |= (1 << CS10);    // Set Timer1 prescaler to 1
                            //   PWM_Freq = F_CPU/1/256
                            //            = 3906.25Hz (assuming F_CPU = 1MHz)
  TCCR1A |= (1 << COM1A1);  // PWM output on pin OC1A (PB1)
  TIMSK1 |= (1 << TOIE1);   // Enable Overflow Interrupt for Timer1
}

int main(void) {
  LED_DDR |= (1 << LED);  // Set LED pin to output
  initTimer1PWM();
  sei();                  // Set global interrupt enable bit
  set_sleep_mode(SLEEP_MODE_IDLE); // Using IDLE sleep mode to save power
                                   // Note that: "If an enabled interrupt occurs while the MCU is in a sleep mode, the MCU wakes up." (in this example it will be Timer1 Overflow Interrupt)

  while(1) {
    sleep_mode();  // Sleep, to save power
  }

  return 0;
}